version: "3.8"
services:
  app:
    container_name: quiz_app
    image: oggieboggie/quiz-app:latest
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production